name: Crawler-Frontend

on:
  schedule:
    - cron : '*/10 * * * *'
  push:
    branches: [ front ]
  pull_request:
    branches: [ front ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: front

      - name: Run
        env:
          DISCORD_FRONT_WEBHOOK: ${{ secrets.DISCORD_FRONT_WEBHOOK }}
          REST_DB_KEY: ${{ secrets.REST_DB_KEY }}
        run: ./gradlew run
