name: Crawler-UXUI

on:
  schedule:
    - cron : '*/10 * * * *'
  push:
    branches: [ design ]
  pull_request:
    branches: [ design ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: design

      - name: Run
        env:
          DISCORD_DESIGN_WEBHOOK: ${{ secrets.DISCORD_DESIGN_WEBHOOK }}
          REST_DB_KEY: ${{ secrets.REST_DB_KEY }}
        run: ./gradlew run
