name: Crawler-iOS

on:
  schedule:
    - cron : '*/10 * * * *'
  push:
    branches: [ ios ]
  pull_request:
    branches: [ ios ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ios

      - name: Run
        env:
          DISCORD_IOS_WEBHOOK: ${{ secrets.DISCORD_IOS_WEBHOOK }}
          REST_DB_KEY: ${{ secrets.REST_DB_KEY }}
        run: ./gradlew run
