name: Crawler-Backend

on:
  schedule:
    - cron : '*/10 * * * *'
  push:
    branches: [ backend-node ]
  pull_request:
    branches: [ backend-node ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_NODE_WEBHOOK: ${{ secrets.DISCORD_NODE_WEBHOOK }}
          REST_DB_KEY: ${{ secrets.REST_DB_KEY }}
        run: ./gradlew run
